server:
  port: 9090

spring:
  profiles:
    active: dev

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9090/oauth2/jwks
          issuer-uri: http://localhost:9090

logging:
  level:
    root: DEBUG
#  org:
#    hibernate:
#      SQL: DEBUG
#      type: TRACE
    springframework:
      security: DEBUG
#      web: DEBUG