server:
  port: 9090

spring:
  mail:
    test-connection: true
    templates:
      path: test-templates

  profiles:
    active: dev

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9090/oauth2/jwks
          issuer-uri: http://localhost:9090


app:
  mail:
    username: jainshashank562@gmail.com
    password: wpjfvcyonutyzdux
    host: smtp.gmail.com
    port: 587
    smtp: true
    tls: true
    debug: true
    testConnection: true
  security:
    login:
      max-count: 3

#logging:
#  level:
#    root: DEBUG
#  org:
#    hibernate:
#      SQL: DEBUG
#      type: TRACE
#    springframework:
#      security: DEBUG
#      web: DEBUG